export type ResponseFindAllObras = {
  Cod_obr: string;
  Empresa_obr: number;
  Descr_obr: string;
  Status_obr: number;
  Ender_obr: string;
  Fone_obr: string;
  Fisc_obr: string;
  DtIni_obr: string | Date;
  Dtfim_obr: string | Date;
  TipoObra_obr: number;
  EnderEntr_obr: string;
  CEI_obr: string | null;
  DataCad_obr: string | Date;
  DataAlt_obr: string | Date;
  UsrCad_obr: string;
};
export type ResponseFindObraWithCode = {
  cod_obr: string;
  Fisc_obr: string;
  descr_obr: string;
  ender_obr: string;
  setor_obr: string;
  cid_obr: string;
  uf_obr: string;
  cep_obr: string;
  dtini_obr: string | Date;
  dtfim_obr: string | Date;
  status_obr: number;
  fone_obr: string;
  fax_obr: string;
  CodGrupo_obr: string;
  TipoObra_obr: number;
  FiscRec_obr: string;
  enderEntr_obr: string;
  setorEntr_obr: string;
  cidEntr_obr: string;
  ufEntr_obr: string;
  cepEntr_obr: string;
  TipoOC_obr: number;
  EmpPaga_obr: string | 'null';
  EmpFatura_obr: string | 'null';
  CodObrNet_obr: string;
  CodCentroCustoNet_obr: string;
  CodEnderEntregaNet_obr: string;
  CodRegiaoNet_obr: string;
  DataCad_obr: string | Date;
  UsrCad_obr: string;
  DataAlt_obr: string | Date;
  UsrAlt_obr: string;
  Anexos_obr: number;
  CarenciaAtraso_obr: number;
  Multa_obr: number;
  Juros_obr: number;
  JurosContrato_obr: number;
  CorrecaoAtr_obr: number;
  TipoUtilFis_Obr: number;
  TipoUtilFin_Obr: number;
  FoneEntr_obr: string;
  FaxEntr_obr: string;
  MesReplanejar_obr: string | 'null';
  ContaPlc_obr: string | 'null';
  ContaBanco_obr: string | 'null';
  NumeroBanco_obr: string | 'null';
  Carteira_obr: string | 'null';
  LotacaoFolha_obr: string;
  CEI_obr: string;
  NumCid_obr: string | 'null';
  NumCidEntr_obr: string | 'null';
  PorcTolEntrega_obr: number;
  ContaBancoPg_obr: string | 'null';
  NumeroBancoPg_obr: string | 'null';
  Empresa_obr: number;
  NumeroBancoAdm_obr: string | 'null';
  ContaBancoAdm_obr: string | 'null';
  CarteiraAdm_obr: string | 'null';
  ValidaFeriado_Obr: number;
  NumSet_obr: string | 'null';
  NumContEmpree_obr: string | 'null';
  NumEmpree_obr: string | 'null';
  ReajusteAnual_obr: number;
  DataLancamento_obr: string | 'null';
  NumCreci_obr: number;
  TipoCreci_obr: string;
  FimAnuncio_obr: string;
  DiaUtil_Obr: boolean;
  EmpresaIntermediadora_Obr: string | 'null';
  EmpSet_obr: string | 'null';
  CustoDesembolso_Obr: boolean;
  DDDFone_Obr: string;
  DDDFoneEntr_Obr: string;
  DDDFax_Obr: string;
  DDDFaxEnt_Obr: string;
  BoletoDetalhado_obr: boolean;
  PorcTxAdm_Obr: number;
  FecharMesAutomatico_obr: boolean;
  TipoCaucaoTxAdm_Obr: boolean;
  CaucaoTxAdm_Obr: number;
  ImpostosTxAdm_Obr: number;
  NumPcbObra_obr: number;
  NumPcbAdm_obr: number;
  NumPcbAvulso_obr: number;
  AtInat_obr: boolean;
  TipoTxAdm_Obr: boolean;
  ApropriarCustoDtPgto_Obr: boolean;
  ProcessoPago_Obr: boolean;
  NumeroBancoBI_obr: string | 'null';
  ContaBi_obr: string | 'null';
  PorcTotPrecoUnit_Obr: number;
  ApontSiAplic_obr: boolean;
  ControlaEstornoPL_obr: boolean;
  FiscFolha_obr: string;
  ParcCustaAdm_obr: boolean;
  ConvenioBancoPg_obr: string | 'null';
  controlaValorLimite_obr: boolean;
  PorcInadimp_obr: number;
  ControleSolicitacao_obr: boolean;
  ObraTipoDepart_Obr: boolean;
  CodGrupoContabil_obr: string | 'null';
  ControlaServExterno_obr: number;
  MaxParcelamento_obr: number;
  ModalidadesCartao_obr: string;
  fiscControleFin_obr: string;
  CodPesObra_obr: number;
  PorcTotPrecoUnitReducao_Obr: number;
  NumPcbAvulsoPIX_obr: string | 'null';
};
